
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    implementation_imports: false
    constant_identifier_names: false
    omit_local_variable_types: false
    avoid_types_on_closure_parameters: false
    use_setters_to_change_properties: false

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - '**/*_test.dart'
    # - '**/*.g.dart'
    # - '**/*.freezed.dart'

